<?php
$storeId = Mage::app()->getStore()->getId();
//Get category model
$_category = Mage::getModel('catalog/category')->setStoreId($storeId);
$_cat = $_category->load(Mage::app()->getStore()->getRootCategoryId());
?>
<?php
    function getChildrenCategoriesHtmlContent($_category){
        $children = explode( ",", $_category->getChildren() );
        $content = '';
        $content .= '<li class="';
        if(!$children[0])
            $content .= 'has-no-children';
        else
            $content .= 'has-children';
        $content .= '">';
        $content .= '<a href="'.$_category->getUrl().'" ';
        $content .= '>'.$_category->getName().'</a>';
        if($children[0]){
            $content .= '<a href="javascript:void(0)" class="plus"><i class="icon-mango-angle-down"></i></a>';
            $content .= '<ul>';
            foreach($children as $child){
                $_subcat = Mage::getModel( 'catalog/category' )->load( $child );
                $content .= getChildrenCategoriesHtmlContent($_subcat);
            }
            $content .= '</ul>';
        }
        $content .= '</li>';
        return $content;
    }
?>
<div class="block block-category-nav">
    <div class="block-title">
        <strong><span><?php echo $this->__("Main Categories") ?></span></strong>
    </div>
    <div class="block-content">
        <ul class="category-list">
            <?php
                $children = explode( ",", $_cat->getChildren() );
                foreach($children as $child){
                    $_category = Mage::getModel( 'catalog/category' )->load( $child );
                    echo getChildrenCategoriesHtmlContent($_category);
                }
            ?>
        </ul>
    </div>
<script type="text/javascript">
    jQuery(function($){
        $(".block.block-category-nav .category-list a.plus").click(function(){
            if($(this).parent().hasClass("opened")){
                $(this).parent().children("ul").slideUp();
                $(this).parent().removeClass("opened");
                $(this).children("i.icon-mango-angle-up").removeClass("icon-mango-angle-up").addClass("icon-mango-angle-down");
            } else {
                $(this).parent().children("ul").slideDown();
                $(this).parent().addClass("opened");
                $(this).children("i.icon-mango-angle-down").removeClass("icon-mango-angle-down").addClass("icon-mango-angle-up");
            }
        });
    });
</script>
</div>