<?php
    $store = Mage::app()->getStore();
    $code  = $store->getCode();
    $_productCollection=$this->getLoadedProductCollection();
    $_helper = $this->helper('catalog/output');
    $aspect_ratio = $this->getAspectRatio();
    $ratio_width = $this->getRatioWidth();
    $ratio_height = $this->getRatioHeight();
	$product_columns = $this->getProductColumns();
	if(!$product_columns || $product_columns < 2 || $product_columns > 8) {
		$product_columns = "6";
	}
?>
<div class="filter-products">
<?php if(!$_productCollection->count()): ?>
    <p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
<?php else: ?>
    <?php $_collectionSize = $_productCollection->count() ?>
    <div class="isotope-products type4 columns<?php echo $product_columns; ?>">
    <?php $i=0; foreach ($_productCollection as $_product): ?>
	<?php
		$product = Mage::getModel('catalog/product')->load($_product->getId());
	?>
        <div class="item isotope-product">
            <div class="item-area">
                <div class="product-image-area">
                    <?php if( !Mage::getStoreConfig("mango_settings/category/hovereffect", $code) ): ?>
                        <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image">
                            <img src="<?php if($aspect_ratio):?><?php echo $this->helper('catalog/image')->init($_product, 'small_image')->constrainOnly(FALSE)->keepAspectRatio(TRUE)->keepFrame(FALSE)->resize(250);?><?php else: ?><?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($ratio_width,$ratio_height); ?><?php endif; ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>"/>
                        </a>
                    <?php elseif(Mage::getStoreConfig("mango_settings/category/hovereffect", $code) == "alternative"): ?>
                        <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image">
                            <img class="defaultImage" src="<?php if($aspect_ratio):?><?php echo $this->helper('catalog/image')->init($_product, 'small_image')->constrainOnly(FALSE)->keepAspectRatio(TRUE)->keepFrame(FALSE)->resize(250);?><?php else: ?><?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($ratio_width,$ratio_height); ?><?php endif; ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>"/>
                            <img class="hoverImage" src="<?php if($aspect_ratio):?><?php echo $this->helper('catalog/image')->init($_product, 'thumbnail')->constrainOnly(FALSE)->keepAspectRatio(TRUE)->keepFrame(FALSE)->resize(250);?><?php else: ?><?php echo $this->helper('catalog/image')->init($_product, 'thumbnail')->resize($ratio_width,$ratio_height); ?><?php endif; ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'thumbnail'), null, true) ?>"/>
                        </a>
                    <?php elseif(Mage::getStoreConfig("mango_settings/category/hovereffect", $code) == "gallery"): ?>
                        <?php
                            $gallery_images = $product->getMediaGalleryImages();
                        ?>
                        <?php if(count($gallery_images) < 1): ?>
                        <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image">
                            <img src="<?php if($aspect_ratio):?><?php echo $this->helper('catalog/image')->init($_product, 'small_image')->constrainOnly(FALSE)->keepAspectRatio(TRUE)->keepFrame(FALSE)->resize(250);?><?php else: ?><?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($ratio_width,$ratio_height); ?><?php endif; ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>"/>
                        </a>
                        <?php else: ?>
                        <div class="owl-product-image-gallery owl-carousel">
                        <?php foreach ($gallery_images as $image): ?>
                        <?php // If no image, skip 
                            if ($image->getFile() == NULL)
                                continue;
                        ?>
                            <div class="item">
                                <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->escapeHtml($image->getLabel()) ?>" class="product-image">
                                    <img src="<?php if($aspect_ratio):?><?php echo $this->helper('catalog/image')->init($_product, 'thumbnail', $image->getFile())->constrainOnly(FALSE)->keepAspectRatio(TRUE)->keepFrame(FALSE)->resize(250);?><?php else: ?><?php echo $this->helper('catalog/image')->init($_product, 'thumbnail', $image->getFile())->resize($ratio_width,$ratio_height); ?><?php endif; ?>" alt="<?php echo $this->escapeHtml($image->getLabel()) ?>"/>
                                </a>
                            </div>
                        <?php endforeach; ?>
                        </div>
                        <?php endif; ?>
                    <?php endif; ?>
                    <?php 
                        
                        $sale_label = false;
                        // Get the Special Price
                        $specialprice = $product->getSpecialPrice(); 
                        // Get the Special Price FROM date
                        $specialPriceFromDate = $product->getSpecialFromDate();
                        // Get the Special Price TO date
                        $specialPriceToDate = $product->getSpecialToDate();
                        // Get Current date
                        $today =  time();
                     
                        if ($specialprice){
                            if($today >= strtotime( $specialPriceFromDate) && $today <= strtotime($specialPriceToDate) || $today >= strtotime( $specialPriceFromDate) && is_null($specialPriceToDate)){
                                if(Mage::getStoreConfig("mango_settings/product_label/sale", $code)){
                                    $sale_label = true;
                    ?>
                                <div class="product-label" style="left: 7px;"><span class="sale-product-icon"><?php echo Mage::getStoreConfig("mango_settings/product_label/sale_label_text", $code);?></span></div>
                    <?php       
                                }
                            }
                        }
                    ?>
                    <?php
                        $now = date("Y-m-d");
                        $newsFrom= substr($_product->getData('news_from_date'),0,10);
                        $newsTo=  substr($_product->getData('news_to_date'),0,10);
                        if ($newsTo != '' || $newsFrom != ''){
                            if (($newsTo != '' && $newsFrom != '' && $now>=$newsFrom && $now<=$newsTo) || ($newsTo == '' && $now >=$newsFrom) || ($newsFrom == '' && $now<=$newsTo))
                            {
                                if(Mage::getStoreConfig("mango_settings/product_label/new", $code)){
                        ?> 
                                <div class="product-label" style="right: 7px;"><span class="new-product-icon"><?php echo Mage::getStoreConfig("mango_settings/product_label/new_label_text", $code);?></span></div>
                        <?php 
                                }
                            }
                        }
                    ?>
                </div>
                <div class="details-area">
                    <h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a></h2>
                    <?php 
                    if(Mage::helper('catalog')->isModuleEnabled('Mage_Review')):
                    if($_product->getRatingSummary()): 
                    ?>
                    <?php 
                        $review_html = $this->getReviewsSummaryHtml($_product, 'short');
                        if($review_html){
                            echo $review_html;
                        }else{
                    ?>
                        <div class="ratings">
                            <div class="rating-box">
                                <div class="rating" style="width:0"></div>
                            </div>
                        </div>
                    <?php                            
                        }
                    ?>
                    <?php else: ?>
                        <div class="ratings">
                            <div class="rating-box">
                                <div class="rating" style="width:0"></div>
                            </div>
                        </div>
                    <?php 
                    endif; 
                    endif;
                    ?>
                    <?php echo $this->getPriceHtml($_product, true) ?>
                </div>
            </div>
        </div>
        <?php endforeach; ?>
		<div class="clearer"></div>
    </div>
<?php endif; ?>
</div>