<?php
    $store = Mage::app()->getStore();
    $code  = $store->getCode();
    $_productCollection=$this->getLoadedProductCollection();
    $_helper = $this->helper('catalog/output');
?>
<?php if(!$_productCollection->count()): ?>
    <p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
<?php else: ?>
    <?php $_collectionSize = $_productCollection->count() ?>
    <ul class="products-list">
    <?php $i=0; foreach ($_productCollection as $_product): ?>
            <li>
                <figure>
                    <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>">
                        <img src="<?php if(Mage::getStoreConfig("mango_settings/category/aspect_ratio",$code)):?><?php echo $this->helper('catalog/image')->init($_product, 'small_image')->constrainOnly(FALSE)->keepAspectRatio(TRUE)->keepFrame(FALSE)->resize(150);?><?php else: ?><?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(Mage::getStoreConfig("mango_settings/category/ratio_width",$code),Mage::getStoreConfig("mango_settings/category/ratio_height",$code)); ?><?php endif; ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image"/>
                    </a>
                </figure>
                <h5 class="product-title"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a></h5>
                <?php 
                if (Mage::helper('catalog')->isModuleEnabled('Mage_Review')):
                ?>
                <?php 
                    $review_html = $this->getReviewsSummaryHtml($_product, 'short');
                    if($review_html){
                        echo $review_html;
                    }else{
                ?>
                    <div class="ratings">
                        <div class="rating-box">
                            <div class="rating" style="width:0"></div>
                        </div>
                    </div>
                <?php                            
                    }
                ?>
                <?php else: ?>
                    <div class="ratings">
                        <div class="rating-box">
                            <div class="rating" style="width:0"></div>
                        </div>
                    </div>
                <?php 
                endif;
                ?>
                <?php echo $this->getPriceHtml($_product, true) ?>
            </li>
        <?php endforeach; ?>
        </ul>
<?php endif; ?>