 
<?php $posts = $this->getPosts(); ?>
<?php if (count($posts)): ?>

<?php foreach ($posts as $post): ?>
    <div class="postWrapper">
        <?php
            if($banner_content = $post->getBannerContent()){
        ?>

        <div class="postBanner">
            <div class="postDate for-mobile"><div><?php echo $post->getDay(); ?></div></div>
            <?php echo $banner_content; ?>
        </div>
        <?php
            }
        ?>
        <div class="postEntry">
            <div class="post-date">
                <span class="day"><?php echo $post->getDay(); ?></span>
                <span class="month"><?php echo $post->getMonthShort(); ?></span>
            </div>
            <div class="postTitle">
                <h2><a href="<?php echo $post->getAddress(); ?>" ><?php echo $post->getTitle(); ?></a></h2>
            </div>
            <div class="postDetails">
                <span><?php echo $this->__('Posted at')?> <?php echo $post->getCreatedTime(); ?></span>
                <span><?php echo $this->__("By"); ?><span class="postAuthor"> <?php echo $post->getUser(); ?></span></span>                                
                <?php $postCats = $post->getCats(); ?>
                <?php if (!empty($postCats)): ?>
                    <span class="seperator">/</span>
                    <span class="postCat"><?php echo $this->__('Category:') ?>
                    <?php $_i = 0; ?>
                    <?php foreach ($postCats as $data): ?>
                        <a href="<?php echo $data['url']; ?>"><?php echo $data['title']; ?></a><?php if($_i++ < (count($postCats) - 1)):?><span class="last">,</span><?php endif; ?>
                    <?php endforeach; ?>
                    </span>
                <?php endif; ?>
            </div>
            <div class="postContent"><?php echo $post->getPostContent(); ?></div>
        </div>
    </div>
<?php endforeach; ?> 
<div class="toolbar-bottom"> 
<?php echo $this->getChildHtml('smartwave_blog_comments_toolbar'); ?>
</div>
<?php else: ?>  
    <p class="note-msg"><?php echo Mage::helper('blog')->__('No Posts in this Category.'); ?></p>
<?php endif; ?>
