<?php $post = $this->getPost(); ?>
<div id="messages_product_view"><?php echo $this->getMessagesBlock()->getGroupedHtml() ?></div>
<div class="postWrapper postSingle">
    <?php if($banner_content = $post->getBannerContent()): ?>
    <div class="postBanner">
    <?php
        echo $banner_content;
    ?>
    </div>
    <?php endif; ?>
    <div class="postTitle">
        <h2><?php echo $post->getTitle(); ?></h2>        
    </div>
    <div class="postDetails">
        <span><?php echo $this->__('Posted at')?> <?php echo $post->getCreatedTime(); ?></span>
        <span><?php echo $this->__("By"); ?><span class="postAuthor"> <?php echo $post->getUser(); ?></span></span>                                
        <?php $postCats = $post->getCats(); ?>
        <?php if (!empty($postCats)): ?>
            <span class="seperator">/</span>
            <span class="postCat"><?php echo $this->__('Category:') ?>
            <?php $_i = 0; ?>
            <?php foreach ($postCats as $title => $url): ?>
                <a href="<?php echo $url; ?>"><?php echo $title; ?></a><?php if($_i++ < (count($postCats) - 1)):?><span>,</span><?php endif; ?>
            <?php endforeach; ?>
            </span>
        <?php endif; ?>
    </div>
    <div class="postContent"><?php echo $post->getPostContent(); ?></div>
    <?php echo $this->getBookmarkHtml($post) ?>
    <div class="tags"><h4><?php echo $this->__('Tag') ?>: </h4><?php echo Mage::getBlockSingleton('blog/blog')->getTagsHtml($post) ?></div>    
</div>

<!-- Comment Section -->

<?php if ($this->getCommentsEnabled()): ?>
<?php $comments = $this->getComment(); ?>    
<?php if(count($comments)): ?>
<div class="postComments">
    <div class="commentTitle"><a name="commentBox" ></a>
        <h2><?php echo $this->__('Comments Posted') ?>(<?php echo count($comments)?>)</h2>
    </div>

    
    <?php foreach ($comments as $comment) : ?>
        <div class="commentWrapper">
            <div class="commentAvartar">
                <img src="<?php echo $this->getSkinUrl('blog/images/blank_avatar.jpg'); ?>" alr="<?php echo $comment->getUser(); ?>" />
            </div>
            <div class="commentContentWrapper">
                  <div class="commentDetails"><h4 class="username"><?php echo $comment->getUser(); ?></h4> (<?php echo $this->__('Posted ')?><?php echo $this->formatDate($comment->getCreatedTime(), Mage::getStoreConfig('blog/blog/dateformat'), true); ?>)</div>
                  <div class="commentContent"><?php echo nl2br($comment->getComment()); ?></div>
            </div>            
        </div>       
    <?php endforeach; ?>    
    <?php // echo $this->getChildHtml('smartwave_blog_comments_toolbar'); ?>
</div>    
<?php endif; ?>
<div class="commentBox">
    <?php if ($post->getComments()): ?>
        <div class="postError"><?php echo Mage::helper('blog')->__('Comments are Closed for this post') ?></div>
    <?php else: ?>
        <?php if ($this->getLoginRequired()): ?>
            <?php if ($this->helper('customer')->isLoggedIn()): ?>
                <form action="" id="postComment" method="post">  
                    <fieldset class="group-select">
                        <div class="commentTitle">
                            <h2><?php echo Mage::helper('blog')->__('Leave a Comment') ?></h2>
                        </div>
                        <ul class="form-list">
                            <li>
                                <div class="input-box smartwave-blog-comment-area">
                                    <label for="comment" class="required"><?php echo Mage::helper('blog')->__('Comment') ?><em>*</em></label><br />
                                    <textarea name="comment" id="comment" title="<?php echo $this->__('Comment') ?>" class="required-entry input-text" cols="50" rows="7" placeholder="<?php echo $this->__('Your message content (required)')?>"><?php echo $this->getCommentText(); ?></textarea>
                                </div>
                            </li>
                        </ul>
                    </fieldset>
                    <div class="button-set" style="width:96%">
                        <input name="post_id" type="hidden" value="<?php echo $post->getPostId(); ?>" />
                        <input name="email" type="hidden" value="<?php echo $this->htmlEscape($this->helper('blog')->getUserEmail()) ?>"/>
                        <input name="user" type="hidden" value="<?php echo $this->htmlEscape($this->helper('blog')->getUserName()) ?>"/>                        
                        <button class="form-button button" type="submit"><span><span><?php echo Mage::helper('blog')->__('Submit Comment') ?></span></span></button>
                    </div>
                </form>

                <script type="text/javascript">
                    var contactForm = new VarienForm('postComment', false);
                </script>            

            <?php else: ?>
                <p><?php echo Mage::helper('blog')->__('You must be logged in to post a comment.'); ?></p>
                <p><a href="<?php echo Mage::helper('customer')->getLoginUrl(); ?>"><?php echo Mage::helper('blog')->__('click here'); ?></a> <?php echo Mage::helper('blog')->__('to log in'); ?></p>
            <?php endif ?>

        <?php else: ?>

            <form action="" id="postComment" method="post">
                <fieldset class="group-select">
                    <div class="commentTitle">
                        <h2><?php echo Mage::helper('blog')->__('Leave a Comment') ?></h2>
                    </div>
                    <ul class="form-list">
                        <li>
                            <div class="row">
                                <div class="col-sm-6">
                                    <div class="input-box">
                                        <label for="name" class="required"><?php echo Mage::helper('blog')->__('Name') ?><em>*</em></label><br />
                                        <input name="user" id="user" value="<?php echo $this->getCommentName(); ?>" title="<?php echo $this->__('Name') ?>" class="required-entry input-text" type="text" placeholder="<?php echo $this->__('Your name (required)') ?>"/>
                                    </div>

                                    <div class="input-box">
                                        <label for="email" class="required"><?php echo Mage::helper('blog')->__('Email') ?><em>*</em></label><br />
                                        <input name="email" id="email" value="<?php echo $this->getCommentEmail(); ?>" title="<?php echo $this->__('Email') ?>" class="required-entry input-text validate-email" type="text" placeholder="<?php echo $this->__('Your email address (required)')?>" />
                                    </div>
                                </div>
                            </div>
                            <div class="clear"></div>

                            <div class="input-box smartwave-blog-comment-area">
                                <label for="comment" class="required"><?php echo Mage::helper('blog')->__('Comment') ?><em>*</em></label><br />
                                <textarea name="comment" id="comment" title="<?php echo Mage::helper('blog')->__('Comment') ?>" class="required-entry input-text" cols="50" rows="7" placeholder="<?php echo $this->__('Your message content (required)')?>"><?php echo $this->getCommentText(); ?></textarea>
                            </div>
                        </li>

                <?php
                        if (Mage::getStoreConfig('blog/recaptcha/enabled') && !$this->helper('customer')->isLoggedIn()) {
                            ?><li><?php
                require_once 'recaptcha/recaptchalib-aw.php';

                // Get a key from http://recaptcha.net/api/getkey
                $publickey = Mage::getStoreConfig('blog/recaptcha/publickey');
                $privatekey = Mage::getStoreConfig('blog/recaptcha/privatekey');
                $error = null;

                echo recaptcha_get_html($publickey, $error);
                            ?></li><?php
            }
                        ?>  
                    </ul>
                </fieldset>
                <div class="button-set" style="width:96%">
                    <input name="post_id" type="hidden" value="<?php echo $post->getPostId(); ?>" />                    
                    <button class="button form-button" type="submit"><span><span><?php echo Mage::helper('blog')->__('Submit Comment') ?></span></span></button>
                </div>
            </form>

            <script type="text/javascript">
                var contactForm = new VarienForm('postComment', false);
            </script>
        <?php endif; ?>
    <?php endif; ?>
</div>
<?php endif; ?>
