<?php
    $store = Mage::app()->getStore();
    $code  = $store->getCode();
    $footer = Mage::getStoreConfig('mango_settings/footer',$code);
?>
<div class="footer-container">
    <div class="footer">
    <?php
        if( $footer['footer_top_enabled'] ){
    ?>
        <div class="footer-top">
            <div class="container">
                <div class="row">
                <?php
                    for( $i = 1; $i <= 6; $i++ ){
                        $area = 'footer_top_column_'.$i;
                        $type = $footer[$area];
                        if( $type ){
                            echo '<div class="col-md-'.$footer[$area.'_size_md'].' col-sm-'.$footer[$area.'_size_sm'].'">';
                        }
                        if( $type == 'custom' ){
                            echo $this->getLayout()->createBlock('cms/block')->setBlockId($footer[$area.'_custom'])->toHtml();
                        }
                        if( $type == 'newsletter' ){
                            echo $this->getChildHtml('footer.newsletter');
                        }
                        if( $type ){
                            echo '</div>';
                        }
                    }
                ?>
                </div>
            </div>
        </div>
    <?php
        }
        if( $footer['footer_middle_enabled'] ){
    ?>
        <div class="footer-middle">
            <div class="container">                
                <div class="row">
                <?php
                    for( $i = 1; $i <= 6; $i++ ){
                        $area = 'footer_middle_column_'.$i;
                        $type = $footer[$area];
                        if( $type ){
                            echo '<div class="col-md-'.$footer[$area.'_size_md'].' col-sm-'.$footer[$area.'_size_sm'].'">';
                        }
                        if( $type == 'custom' ){
                            echo $this->getLayout()->createBlock('cms/block')->setBlockId($footer[$area.'_custom'])->toHtml();
                        }
                        if( $type == 'newsletter' ){
                            echo $this->getChildHtml('footer.newsletter');
                        }
                        if( $type ){
                            echo '</div>';
                        }
                    }
                ?>
                </div>
                <?php echo $this->getChildHtml("demo_footer_tooltip"); ?>
            </div>
        </div>
    <?php
        }
        if( $footer['footer_bottom_enabled'] ){
    ?>
        <div class="footer-bottom">
            <div class="container">
            <?php
                echo $this->getLayout()->createBlock('cms/block')->setBlockId($footer['footer_bottom_custom'])->toHtml();
            ?>
            </div>
        </div>
    <?php
        }
    ?>
    </div>
</div>
<a href="#" id="totop"><i class="icon-mango-angle-up"></i></a>
<script type="text/javascript">
    var windowScroll_t;
    jQuery(window).scroll(function(){
        clearTimeout(windowScroll_t);
        windowScroll_t = setTimeout(function(){
            if(jQuery(this).scrollTop() > 100){
                jQuery('#totop').fadeIn();
            }else{
                jQuery('#totop').fadeOut();
            }
        }, 500);
    });
    jQuery('#totop').click(function(){
        jQuery('html, body').animate({scrollTop: 0}, 600);
        return false;
    });
</script>