<?php echo $this->getChildHtml('sticky.nav') ?>
<?php
    $store = Mage::app()->getStore();
    $code  = $store->getCode();
    $custom_block_id = Mage::getStoreConfig('mango_settings/header/static_block', $code);
    $store_language = $this->getChildHtml('store_language');
    $store_currency = $this->getChildHtml('store_currency');
    $compare_link = $this->getChildHtml('compare_link');
    $custom_block = "";
    if($custom_block_id){
        $custom_block = $this->getLayout()->createBlock('cms/block')->setBlockId($custom_block_id)->toHtml();
    }
?>
<div class="header-container type10">
    <div class="header">
        <a href="<?php echo $this->getUrl(''); ?>" title="<?php echo $this->getLogoAlt(); ?>" class="logo"><img src="<?php echo $this->getLogoSrc(); ?>" alt="<?php echo $this->getLogoAlt(); ?>" /></a>
        <div class="search-area">
            <a href="javascript:void(0);" class="search-icon"><i class="icon-mango-search"></i></a>
            <?php echo $this->getChildHtml('topSearch'); ?>
        </div>
        <div class="header-right">
            <div class="menu-icon"><a href="javascript:void(0)"><i class="icon-mango-nav-icon"></i></a></div>
            <?php
                echo $this->getChildHtml('minicart');
            ?>            
        </div>
        <?php echo $this->getChildHtml("demo_header_tooltip"); ?>
        <div class="side-menu">
            <?php echo $this->getChildHtml('topMenu') ?>
        </div>
        <?php
            echo ($custom_block)?'<div class="custom-block">'.$custom_block.'</div>':'';
        ?>
    </div>
</div>
<?php echo $this->getChildHtml('mobile.nav') ?>
