<?php echo $this->getChildHtml('sticky.nav') ?>
<?php
    $store = Mage::app()->getStore();
    $code  = $store->getCode();
    $custom_block_id = Mage::getStoreConfig('mango_settings/header/static_block', $code);
    $store_language = $this->getChildHtml('store_language');
    $store_currency = $this->getChildHtml('store_currency');
    $compare_link = $this->getChildHtml('compare_link');
    $custom_block = "";
    if($custom_block_id){
        $custom_block = $this->getLayout()->createBlock('cms/block')->setBlockId($custom_block_id)->toHtml();
    }
?>
<div class="header-container type11">
    <div class="header">
        <div class="header-top">
            <div class="container">
                <div class="header-top-left">
                    <?php 
                        echo $store_language;
                        if($store_language){
                            echo '<span class="split"></span>';
                        }
                        echo $store_currency;
                        if($store_currency){
                            echo '<span class="split"></span>';
                        }
                        echo ($custom_block)?'<div class="custom-block">'.$custom_block.'</div>':'';
                        if($custom_block){
                            echo '<span class="split"></span>';
                        }
                    ?>
                    <div class="top-links-area">
                        <div class="top-links-icon"><a href="javascript:void(0)"><?php echo Mage::getStoreConfig('mango_settings/header/toplinks_text', $code); ?></a></div>
                        <?php echo $this->getChildHtml('topLinks'); ?>
                    </div>
                </div>
                <div class="header-top-right">
                    <?php
                        echo $compare_link;
                    ?>
                    <?php echo $this->getChildHtml('minicart'); ?>
                </div>
            </div>
        </div>
        <div class="container">
            <a href="<?php echo $this->getUrl(''); ?>" title="<?php echo $this->getLogoAlt(); ?>" class="logo"><img src="<?php echo $this->getLogoSrc(); ?>" alt="<?php echo $this->getLogoAlt(); ?>" /></a>
            <?php echo $this->getChildHtml("demo_header_tooltip"); ?>
            <div class="menu-icon"><a href="javascript:void(0)"><i class="icon-mango-nav-icon"></i></a></div>
        </div>
        <div class="container">
            <div class="header-bottom">
                <?php echo $this->getChildHtml('topMenu') ?>
            </div>
        </div>
    </div>
</div>
<?php echo $this->getChildHtml('mobile.nav') ?>
