<?php echo $this->getChildHtml('sticky.nav') ?>
<?php
    $store = Mage::app()->getStore();
    $code  = $store->getCode();
    $custom_block_id = Mage::getStoreConfig('mango_settings/header/static_block', $code);
    $store_language = $this->getChildHtml('store_language');
    $store_currency = $this->getChildHtml('store_currency');
    $custom_block = "";
    if($custom_block_id){
        $custom_block = $this->getLayout()->createBlock('cms/block')->setBlockId($custom_block_id)->toHtml();
    }
?>
<div class="header-container type8">
    <div class="container">
        <div class="header">
            <a href="<?php echo $this->getUrl(''); ?>" title="<?php echo $this->getLogoAlt(); ?>" class="logo"><img src="<?php echo $this->getLogoSrc(); ?>" alt="<?php echo $this->getLogoAlt(); ?>" /></a>
            <div class="header-right">
                <?php echo $this->getChildHtml('minicart'); ?>
                <div class="top-links-area">
                    <div class="top-links-icon"><a href="javascript:void(0)"><i class="icon-mango-user"></i></a></div>
                    <?php echo $this->getChildHtml('topLinks'); ?>
                </div>
                <div class="search-area">
                    <a href="javascript:void(0);" class="search-icon"><i class="icon-mango-search"></i></a>
                    <?php echo $this->getChildHtml('topSearch'); ?>
                </div>
                <?php echo $this->getChildHtml('topMenu') ?>
                <div class="menu-icon"><a href="javascript:void(0)"><i class="icon-mango-nav-icon"></i></a></div>
                <?php echo $this->getChildHtml("demo_header_tooltip"); ?>
            </div>            
        </div>
    </div>
</div>
<?php echo $this->getChildHtml('mobile.nav') ?>
