<style type="text/css">
	@font-face {
        font-family: Montserrat;
        src: url(http://fonts.googleapis.com/css?family=Montserrat);
	}
	.header {
		display: none;
	}
	.top-container {
		display: none;
	}
	.nothing {

		text-align: center;
		margin-top: 100px;
		font-family: 'Montserrat', sans-serif;
	}
	.nothing .nothing-wrapper {
		padding: 30px;
	    background: #ECA456;
	    border-radius: 5px;
        box-shadow: 0px 3px 1px #353535;
        display: block;
	    width: 300px;
	    margin: 0 auto;
	}
	.nothing .nothing-wrapper i {
		font-size: 3em;
		display: block;
	}
	.nothing .nothing-wrapper span.sorry {
		
	    font-size: 2em;
	    text-transform: uppercase;
	    color: #333;
	    margin-top: 100px;
        text-shadow: 0px 1px 0px #BBB;
		font-weight: bold;
	}
</style>

<div class="nothing">
	<span class="nothing-wrapper">
		<i class="fa fa-exclamation-triangle"></i>
		<span class="sorry">Sorry, wait until you turn 18.</span>
	</span>
</div>