<script type="text/javascript">
	jQuery(function($){
		var scrolled = false;
		$(window).scroll(function(){
			if(450<$(window).scrollTop() && !scrolled){
				$('.header-container').addClass("sticky-header");
				$('.header-container .header-wrapper > div').each(function(){
					if($(this).hasClass("container")){
						$(this).addClass("already");
					} else {
						$(this).addClass("container");
					}
				});
				scrolled = true;
			}
			if(450>=$(window).scrollTop() && scrolled){
				$('.header-container').removeClass("sticky-header");
				scrolled = false;
				$('.header-container .header-wrapper > div').each(function(){
					if($(this).hasClass("already")){
						$(this).removeClass("already");
					} else {
						$(this).removeClass("container");
					}
				});
			}
		});
	});
</script>