<?php
/**
 Made by Smartwave.
 */
?>
<?php
    $store = Mage::app()->getStore();
    $code  = $store->getCode();
    $popup = Mage::getStoreConfig('mango_settings/newsletter_popup',$code);
?>
<script type="text/javascript">
    jQuery(function($) {
        var check_cookie = $.cookie('newsletter_popup');
        if(check_cookie == null || check_cookie == 'shown') {
            beginNewsletterForm();
        }
        $('#newsletter_popup_dont_show_again').on('change', function(){
            if($(this).length){        
                var check_cookie = $.cookie('newsletter_popup');
                if(check_cookie == null || check_cookie == 'shown') {
                    $.cookie('newsletter_popup','dontshowitagain');            
                }
                else
                {
                    $.cookie('newsletter_popup','shown');
                    beginNewsletterForm();
                }
            } else {
                $.cookie('newsletter_popup','shown');
            }
        }); 
    });

function beginNewsletterForm() {
    /*jQuery.fancybox({
        'padding': '0px',
        'autoScale': true,
        'transitionIn': 'fade',
        'transitionOut': 'fade',
        'type': 'inline',
        'href': '#newsletter_popup',
        'onComplete': function() {
            $.cookie('newsletter_popup', 'shown');
        },
        'tpl': { 
            closeBtn: '<a title="Close" class="fancybox-item fancybox-close fancybox-newsletter-close" href="javascript:;"></a>' 
        },
        'helpers': {
            overlay : {
                locked  : false
            }
        }
    });*/
    /*jQuery('#newsletter_popup').trigger('click');*/
}
function getAge(birthDateString) {
    var today = new Date();
    var birthDate = new Date(birthDateString);
    var age = today.getFullYear() - birthDate.getFullYear();
    var m = today.getMonth() - birthDate.getMonth();
    if (m < 0 || (m === 0 && today.getDate() < birthDate.getDate())) {
        age--;
    }
    return age;
}
function addBirthDate() {
    
    jQuery(".verify-age").fadeOut();
    jQuery(".verify-birthdate").fadeIn();
}
function closePopUp() {
    var now = new Date(),
        birthdate = '';
        time = now.getTime();
            time += 3600 * 1000;
            now.setTime(time);

    birthdate = jQuery("#verify-datepicker").val();
    if(getAge(birthdate) >= 18) {
        document.cookie = 'username=kingdavid_visitor' + '; expires=' + now + '; path=/';
        document.cookie = 'birthdate=' + birthdate + '; expires=' + now + '; path=/';
        jQuery("#check-wrapper").fadeOut();
        jQuery(".over-lay").hide();
    }
    else {
        alert("Seems like you are under 18.");
        window.location.href = "http://local.kingdavid.ph/nothing";
    }
}
jQuery(document).ready(function(){
    if(document.cookie.indexOf("kingdavid_visitor") != -1) {
        jQuery("#check-wrapper").hide();
        jQuery(".over-lay").hide();
    }
    jQuery("#verify-datepicker").datepicker({ 
        yearRange: "-20:+18", // this is the option you're looking for
        showOn: "both", 
        buttonImage: "skin/frontend/base/default/images/calendar-128.png", 
        buttonImageOnly: true 
    });
});
</script>
<style type="text/css">
    .over-lay {
        font-family: 'Open Sans', sans-serif;
        font-style: normal;
        font-weight: 400;
        position: fixed;
        top: 0;
        left: 0;
        z-index: 9999;
        width: 100%;
        height: 100%;
        background: rgba(37, 37, 37, 0.55);
    }
    .check-wrapper {
        position: fixed;
        z-index: 10000;
        width: 400px;
        left: 37%;
        top: 50px;
        padding: 10px;
        border-radius: 4px;
        box-shadow: 0px 4px 6px 1px rgba(0, 0, 0, 0.43);
        background: rgba(64, 64, 64, 0.69);
    }
    .check-wrapper .check {
        margin: 0 auto;
        padding: 20px;
        background: #fff;
        border-radius: 4px;
    }
    .check-wrapper .check img {
        width: 300px;
        display: block;
        margin: 0 auto;
    }
    .check-wrapper .check span {
        display: block;
        text-align: center;
    }
    .check-wrapper .check .welcome {
        font-weight: 600;
        text-transform: uppercase;
    }
    .check-wrapper .check .intention {
        color: #717171;
        text-align: justify;
    }
    .check-wrapper .check .title {
        font-size: 2.5em;
        text-transform: uppercase;
        font-weight: 700;
        color: #484848;
        text-shadow: 0 2px 1px #969696;
    }
    .selection {
        margin-top: 20px;
        display: block;
        width: 100%;
        text-align: center;
    }
    .selection .over18 ,.selection .under18 {
        margin-top: 10px;
        -webkit-border-radius: 4px;
        -moz-border-radius: 4px;
        border-radius: 4px;
        font-size: 13px;
        font-weight: bold;
        text-align: center;
        line-height: 28px;
        text-shadow: 0px 1px 0px rgba(255,255,255,.4);
        -webkit-transition: all 1s ease;
    }
    .selection .under18 a {
        display: block;
        padding: 10px;
    }
    .selection .over18 i ,.selection .under18 i {
        margin-left: 5px;
    }
    .selection .over18 {
        padding: 10px;
        color: #fff;
        background-image: -webkit-linear-gradient(top, rgb(254, 218, 113), rgb(254, 186, 72));
        background-image: -moz-linear-gradient(top, rgb(254, 218, 113), rgb(254, 186, 72));
        background-image: -o-linear-gradient(top, rgb(254, 218, 113), rgb(254, 186, 72));
        background-image: -ms-linear-gradient(top, rgb(254, 218, 113), rgb(254, 186, 72));
        background-image: linear-gradient(top, rgb(254, 218, 113), rgb(254, 186, 72));
        filter: progid:DXImageTransform.Microsoft.gradient(GradientType=0,StartColorStr='#feda71', EndColorStr='#feba48');
        border: 1px solid #ca9336;
        -webkit-box-shadow: inset 0px 1px 0px #fee395, 0px 1px 1px rgba(0,0,0,.15);
        -moz-box-shadow: inset 0px 1px 0px #fee395, 0px 1px 1px rgba(0,0,0,.15);
        box-shadow: inset 0px 1px 0px #fee395, 0px 1px 1px rgba(0,0,0,.15);
        color: #996633;
       
    }
    .selection .under18 {
        background: -webkit-linear-gradient(top, rgba(248,114,136,1) 0%,rgba(243,71,85,1) 90%,rgba(225,65,77,1) 95%,rgba(206,59,70,1) 100%);
        background: -moz-linear-gradient(top, rgba(248,114,136,1) 0%,rgba(243,71,85,1) 90%,rgba(225,65,77,1) 95%,rgba(206,59,70,1) 100%);
        background: -o-linear-gradient(top, rgba(248,114,136,1) 0%,rgba(243,71,85,1) 90%,rgba(225,65,77,1) 95%,rgba(206,59,70,1) 100%);
        background: -ms-linear-gradient(top, rgba(248,114,136,1) 0%,rgba(243,71,85,1) 90%,rgba(225,65,77,1) 95%,rgba(206,59,70,1) 100%);
        background: linear-gradient(top, rgba(248,114,136,1) 0%,rgba(243,71,85,1) 90%,rgba(225,65,77,1) 95%,rgba(206,59,70,1) 100%);
        filter: progid:DXImageTransform.Microsoft.gradient( startColorstr='#f87288', endColorstr='#ce3b46',GradientType=0 );
        border: 1px solid #b0333e;
        color:#fff;
    }
    .selection .over18:hover {
        background-image: -webkit-linear-gradient(top, rgb(254, 194, 82), rgb(254, 205, 97));
        background-image: -moz-linear-gradient(top, rgb(254, 194, 82), rgb(254, 205, 97));
        background-image: -o-linear-gradient(top, rgb(254, 194, 82), rgb(254, 205, 97));
        background-image: -ms-linear-gradient(top, rgb(254, 194, 82), rgb(254, 205, 97));
        background-image: linear-gradient(top, rgb(254, 194, 82), rgb(254, 205, 97));
        filter: progid:DXImageTransform.Microsoft.gradient(GradientType=0,StartColorStr='#fec252', EndColorStr='#fecd61');
     
        -webkit-box-shadow:
            inset 0px 1px 0px #fed17e,
                  0px 1px 1px rgba(0,0,0,.1);
        -moz-box-shadow:
            inset 0px 1px 0px #fed17e,
                  0px 1px 1px rgba(0,0,0,.1);
        box-shadow:
            inset 0px 1px 0px #fed17e,
                  0px 1px 1px rgba(0,0,0,.1);
        cursor: pointer;
    }
    .selection .under18:hover {
        background: -webkit-linear-gradient(top, rgba(206,59,70,1) 100%, rgba(225,65,77,1) 95%, rgba(243,71,85,1) 90%, rgba(248,114,136,1) 0%);
        background: -moz-linear-gradient(top, rgba(206,59,70,1) 100%, rgba(225,65,77,1) 95%, rgba(243,71,85,1) 90%, rgba(248,114,136,1) 0%);
        background: -o-linear-gradient(top, rgba(206,59,70,1) 100%, rgba(225,65,77,1) 95%, rgba(243,71,85,1) 90%, rgba(248,114,136,1) 0%);
        background: -ms-linear-gradient(top, rgba(206,59,70,1) 100%, rgba(225,65,77,1) 95%, rgba(243,71,85,1) 90%, rgba(248,114,136,1) 0%);
        background: linear-gradient(top, rgba(206,59,70,1) 100%, rgba(225,65,77,1) 95%, rgba(243,71,85,1) 90%, rgba(248,114,136,1) 0%);
        filter: progid:DXImageTransform.Microsoft.gradient( startColorstr='#f87288', endColorstr='#ce3b46',GradientType=0 );
        border: 1px solid #b0333e;
        cursor: pointer;
    }
    .verify-birthdate input[type=text] {
        width: 85%;
        float: left;
        margin-bottom: 20px;
        font-weight: bold;
    }
    .verify-birthdate img {
        float: right;
        width: 35px !important;
        margin-top: -2px !important;
    }
    .verify-birthdate button {
        width: 100%;
        padding: 10px;
    }
    .copyright {
        text-align: center; 
        margin-top: 15px;
        font-size: 0.8em;
        color: #C1C1C1;
    }
    .verify-birthdate {
        display: none; 
    }
    @media screen and (max-width: 430px) {
        .check-wrapper {
            left: 10%;
            width: 330px;
        }
        .check-wrapper .check img {
            width: 250px;
        }
        .check-wrapper .check .intention {
            font-size: 0.8em;
        }
        .selection .over18, .selection .under18 {
            padding: 5px;
        }
    }
    @media screen and (min-width: 431px) {
        .check-wrapper {
            left: 15%;
            width: 330px;
        }
        .check-wrapper .check img {
            width: 260px;
        }
    }
    @media screen and (min-width: 640px) {
        .check-wrapper {
            left: 15%;
            width: 400px;
        }
        .check-wrapper .check img {
            width: 300px;
        }
    }
    @media screen and (min-width: 768px) {
        .check-wrapper {
            left: 24%;
            
        }
    }
    @media screen and (min-width: 992px) {
        .check-wrapper {
            left: 37%;
            
        }
    }

</style>
<div class="block block-subscribe" id="newsletter_popup">
</div>
<div class="check-wrapper" id="check-wrapper">
    <div class="check">
        <div class="verify-age">
            <div>
                <span class="welcome">Welcome to</span>
                <span class="title">King David PH</span>
                    <img src="http://store.staging.shop.esh.ph/skin/frontend/rb/default/images/logo.png">
                <span class="intention"><b>King David Fineries</b> makes sure that our product will only be sold to people of legal smoking age. Please verify your age to proceed.</span>
            </div>
            <div class="selection">
                <div class="over18" onClick="addBirthDate();">
                    Yes, I am over 18 <i class="fa fa-thumbs-up"></i>
                </div>
                <div class="under18">
                    <a href='/nothing'>Oops! Im outta here! <i class="fa fa-frown-o"></i></a>
                </div>
            </div>
        </div>
        <div class="verify-birthdate">
            <h1>Enter Your Birthdate</h1>
            <input type="text" class="form-control" id="verify-datepicker" placeholder="MM/DD/YYYY">
            <button onClick="closePopUp();">Continue</button>
        </div>
        <div class="copyright">
            &#169;  KING DAVID PH 2015
        </div>
    </div>
    
    
</div>
<div class="over-lay"></div>
